### ISSUE TITLE
Error while installing

### ISSUE THREAD

**Issue by SSoroushS** [GingerAvalanche/botw_actor_tool#18]
getting these errors while trying to install the tool

 Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [31 lines of output]
 

 AttributeError: module 'configparser' has no attribute 'SafeConfigParser'. Did you mean: 'RawConfigParser'?
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

![Screenshot 2024-06-11 102225](https://github.com/GingerAvalanche/botw_actor_tool/assets/148548951/6c7ccd00-f0f9-4b19-b99c-bc6859aa93ad)
![Screenshot 2024-06-11 102300](https://github.com/GingerAvalanche/botw_actor_tool/assets/148548951/8edc681c-ed72-4183-81e2-1463ebb227ee)

**Comment by GingerAvalanche** [comment]
Python 3.12 got rid of a thing that was necessary to build oead, the backing library for this tool. It only works on 3.7 to 3.11, until oead can be updated.
